# Generated by Django 4.0.4 on 2022-05-29 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("title", models.TextField(blank=True, null=True)),
                ("artist", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("label", models.TextField(blank=True, null=True)),
                ("path", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "album",
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("title", models.TextField(blank=True, null=True)),
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("track_id", models.IntegerField(blank=True, null=True)),
                ("genre", models.TextField(blank=True, null=True)),
                ("artist", models.TextField(blank=True, null=True)),
                ("composer", models.TextField(blank=True, null=True)),
                ("performer", models.TextField(blank=True, null=True)),
                ("file", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="orm.album"
                    ),
                ),
            ],
            options={
                "db_table": "song",
            },
        ),
    ]
